#!/usr/bin/env python3
"""
Generate a delta report between two corpus sources (Part 4 pilot: CR r8 vs r9).

Compares the heading-level structure and section text of two chunked sources
and writes a Markdown report to rag/reports/. Designed for the roadmap Phase 3
pilot (Low-Latency Live CR r8 vs r9), but works for any two source ids that
have been extracted and chunked.

Heuristics (stdlib only):
- Group chunks by heading per source.
- Report headings only in A, only in B, and in both.
- For shared headings, report a rough similarity and flag likely changes.

Usage:
    python tools/migration/delta_report.py cr-low-latency-live-r8 cr-low-latency-live-r9
    python tools/migration/delta_report.py A_ID B_ID --out custom-report.md
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHUNKS = ROOT / "rag" / "chunks"
REPORTS = ROOT / "rag" / "reports"

TOKEN = re.compile(r"[A-Za-z0-9]+")


def load_source(source_id: str) -> dict[str, str]:
    """Return {heading: concatenated_text} for a chunked source."""
    path = CHUNKS / f"{source_id}.jsonl"
    if not path.exists():
        raise SystemExit(
            f"No chunks for '{source_id}'. Extract and chunk it first "
            f"(expected {path.relative_to(ROOT)})."
        )
    by_heading: dict[str, list[str]] = defaultdict(list)
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        record = json.loads(line)
        heading = record.get("heading") or "(no heading)"
        by_heading[heading].append(record.get("text", ""))
    return {h: "\n".join(v) for h, v in by_heading.items()}


def similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, a, b).ratio()


def build_report(a_id: str, b_id: str, a: dict[str, str], b: dict[str, str]) -> str:
    a_keys = set(a)
    b_keys = set(b)
    only_a = sorted(a_keys - b_keys)
    only_b = sorted(b_keys - a_keys)
    shared = sorted(a_keys & b_keys)

    lines = [
        f"# Delta report: `{a_id}` vs `{b_id}`",
        "",
        "Generated by `tools/migration/delta_report.py` from chunked corpus text.",
        "This is a heuristic structural diff to support editorial reconciliation, "
        "not an authoritative redline.",
        "",
        "## Summary",
        "",
        f"- Headings only in **{a_id}**: {len(only_a)}",
        f"- Headings only in **{b_id}**: {len(only_b)}",
        f"- Shared headings: {len(shared)}",
        "",
        f"## Headings only in `{a_id}` (removed / renamed)",
        "",
    ]
    lines += [f"- {h}" for h in only_a] or ["- (none)"]

    lines += ["", f"## Headings only in `{b_id}` (added / renamed)", ""]
    lines += [f"- {h}" for h in only_b] or ["- (none)"]

    lines += ["", "## Shared headings with content changes", "",
              "| Heading | Similarity | Likely change |", "|---|---|---|"]
    changed = 0
    for heading in shared:
        ratio = similarity(a[heading], b[heading])
        if ratio < 0.98:
            flag = "major" if ratio < 0.6 else "minor"
            safe = heading.replace("|", "\\|")
            lines.append(f"| {safe} | {ratio:.2f} | {flag} |")
            changed += 1
    if changed == 0:
        lines.append("| (none) | - | - |")

    lines += [
        "",
        "## Suggested editor follow-ups",
        "",
        "- Review 'major' changes for normative-keyword shifts (shall/should/may).",
        "- Confirm renamed headings map to the same concept before merging.",
        "- Capture unresolved items as GitHub issues tagged with the target part.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("a_id", help="First source id (baseline)")
    parser.add_argument("b_id", help="Second source id (comparison)")
    parser.add_argument("--out", help="Output filename under rag/reports/")
    args = parser.parse_args()

    a = load_source(args.a_id)
    b = load_source(args.b_id)
    report = build_report(args.a_id, args.b_id, a, b)

    REPORTS.mkdir(parents=True, exist_ok=True)
    out_name = args.out or f"delta-{args.a_id}-vs-{args.b_id}.md"
    out_path = REPORTS / out_name
    out_path.write_text(report, encoding="utf-8")
    print(f"Wrote {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
